#!/bin/bash -l 
#SBATCH -A uppmax2026-1-61
#SBATCH -p pelle
#SBATCH -c 1
#SBATCH -t 02:00:00
#SBATCH -J 1_01_trimmomatic_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aljo6352@student.uu.se
#SBATCH --output=%x.%j.out #IS this needed??

#load modules 

module load Trimmomatic

#define variables/paths

TRIMMOMATIC="/sw/arch/eb/software/Trimmomatic/0.39-Java-17/trimmomatic-0.39.jar"  
BASEPATH="{$HOME}/genome_analysis/project_GA/"
LOG="{$BASEPATH}/analyses_outputs/1_preprocessing/1_01_log.txt"
INPUT_R1="{$BASEPATH}/data/raw_data/chr3_illumina_R1.fq.gz"
INPUT_R2="{$BASEPATH}/data/raw_data/chr3_illumina_R2.fq.gz"

OUTPATH="{$BASEPATH}/data/processed_data/1_01_trimmed/"
FP="{$OUTPATH}/fw_paired"
RP="{$OUTPATH}/rv_paired"
FUP="{$OUTPATH}/fw_unpaired"
RUP="{$OUTPATH}/rv_unpaired"


#run
java -jar $TRIMMOMATIC PE [-trimlog $LOG] >] $INPUT_R1 INPUT_R2 $FP $FUP $RP $RUP <step 1> ..
#NEED to add steps. 
